[guest-one]
guest_id                = "6f6df621-42e5-4579-99d8-969e592c1f2b"

[guest-one.user_profile]
first_name              = "Guest"
last_name               = "One"
role                    = "an role 1"
organisation            = "an organisation 1"
sector                  = "a sector"
size_of_organisation    = "a size"
country                 = "a country"
linkedin                = "a linkedin profile"
additional_system_prompt= "an additional prompt"

[guest-two]
guest_id                = "686a35ef-f78d-4158-a240-11e296cd187a"

[guest-two.user_profile]
first_name              = "Guest"
last_name               = "Two"
role                    = "Board Member 2"
organisation            = "Retail R'Us"
sector                  = "Retail"
size_of_organisation    = "a size"
country                 = "UK"
linkedin                = "a linkedin profile"
additional_system_prompt= "an additional prompt"

[guest-three]
guest_id                = "7a43a0e0-499f-4110-8923-441a7f5028db"

[guest-three.user_profile]
first_name              = "Guest"
last_name               = "Three"
role                    = "Board Member 3"
organisation            = "an organisation 3"
sector                  = "a sector"
size_of_organisation    = "a size"
country                 = "a country"
linkedin                = "a linkedin profile"
additional_system_prompt= "an additional prompt"
