[user_1]
first_name = "User"
last_name  = "One"
session_id = "user_1__a824e9a4-838d-1111-2222-440de756637b"
user_id    = "a824e9a4-838d-4790-9bfe-440de756637b"
user_name  = "user_1"



[user_2]
first_name = "User"
last_name  = "Two"
session_id = "user_2__0e81dc75-aaaa-bbbb-90f4-b7dab0681d95"
user_id    = "0e81dc75-31a7-411e-90f4-b7dab0681d95"
user_name  = "user_2"
