[home]
    href = 'home'
    icon = 'mdi-home'
    text = 'Home'
    logged_in = false
    visibility = true
[athena]
    href = 'athena'
    icon = 'mdi-robot'
    text = 'Athena'
    logged_in = false
    visibility = true
[content]
    href = 'content'
    icon = 'mdi-security'
    text = 'Security content'
    logged_in = false
    visibility = true
[videos]
    href = 'content/videos'
    icon = 'mdi-video'
    text = 'Videos'
    logged_in = false
    visibility = true
[docs]
    href = 'docs'
    icon = 'mdi-book-multiple-variant'
    text = 'Docs'
    logged_in = false
    visibility = true
[profile]
    href = 'user/profile'
    icon = 'mdi-account-check'
    text = 'Profile'
    logged_in = true
    visibility = 'config.LOGIN_ENABLED'
[dev]
    href = 'dev'
    icon = 'mdi-developer-board'
    text = 'Dev'
    logged_in = true
    visibility = "g.user_groups and 'CBR-Team' in g.user_groups"
[minerva]
    href = 'minerva'
    icon = 'mdi-robot'
    text = 'Minerva'
    logged_in = true
    visibility = "g.user_groups and 'CBR-Team' in g.user_groups"
[logout]
    href = 'sign-out'
    icon = 'mdi-logout'
    text = 'Logout'
    logged_in = true
    visibility = "current_user.get('username')"
[login]
    href = 'login'
    icon = 'mdi-login'
    text = 'Login'
    logged_in = true
    visibility = "config.LOGIN_ENABLED and not current_user.get('username')"
[restore_admin_user]
    href = 'admin/restore_admin_user'
    icon = 'mdi-restore'
    text = 'RESTORE ADMIN USER'
    logged_in = true
    visibility = "current_user.get('admin_token') and current_user.get('impersonating')"
[chat_with_llms]
    href = 'chat-with-llms'
    icon = 'mdi-message'
    text = 'Chat with LLMs'
    logged_in = false
    visibility = true
[community_discord]
    href = 'https://discord.gg/HdJJbFpzMX'
    icon = 'mdi-message'
    text = 'Community (Discord)'
    logged_in = false
    visibility = true