[home]
    href = 'home'
    icon = 'mdi-home'
    text = 'Home'
    logged_in = false
    visibility = true
[athena]
    href = 'athena'
    icon = 'mdi-robot'
    text = 'Athena'
    logged_in = false
    visibility = true
[content]
    href = 'content'
    icon = 'mdi-security'
    text = 'Security content'
    logged_in = false
    visibility = true