name       : CI Pipeline - MAIN
on:
  push:
    branches:
      - main

env:
  GIT__BRANCH         : 'main'
  PACKAGE_NAME        : 'cbr_content'
  RELEASE_TYPE        : 'major'

jobs:

  increment-tag:
    name: Increment Tag - MAIN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag (for MAIN)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type : ${{env.RELEASE_TYPE}}

  publish-to-pypi:
    permissions:
      id-token: write
    name: "Publish to PYPI"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__publish@dev
    needs:
      - increment-tag


    trigger-deploy-community-dev:
      name: "Deploy Community (DEV)"
      runs-on: ubuntu-latest
      steps:
        - name: Trigger target repository workflow
          run: |
            curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GIT_HUB__ACCESS_TOKEN }}" \
            https://api.github.com/repos/the-cyber-boardroom/cbr-community/dispatches \
            -d '{"event_type":"deploy-community-dev"}'
      needs:
        - increment-tag
